Bedrijfstak.create("letter"=>"A", "naam"=>"Landbouw, bosbouw en visserij")
Bedrijfstak.create("letter"=>"B", "naam"=>"Delfstoffenwinning")
Bedrijfstak.create("letter"=>"C", "naam"=>"Industrie")
Bedrijfstak.create("letter"=>"D", "naam"=>"Energie- en waterleidingbedrijven")
Bedrijfstak.create("letter"=>"E", "naam"=>"Water en afvalwater")
Bedrijfstak.create("letter"=>"F", "naam"=>"Bouwnijverheid")
Bedrijfstak.create("letter"=>"G", "naam"=>"Groot- en detailhandel")
Bedrijfstak.create("letter"=>"H", "naam"=>"Vervoer, opslag en communicatie")
Bedrijfstak.create("letter"=>"I", "naam"=>"Horeca")
Bedrijfstak.create("letter"=>"J", "naam"=>"Informatie en communicatie")
Bedrijfstak.create("letter"=>"K", "naam"=>"Financi\xC3\xABle instellingen")
Bedrijfstak.create("letter"=>"L", "naam"=>"Onroerend goed")
Bedrijfstak.create("letter"=>"M", "naam"=>"Zakelijke dienstverlening ")
Bedrijfstak.create("letter"=>"N", "naam"=>"Overige zakelijke dienstverlening")
Bedrijfstak.create("letter"=>"O", "naam"=>"Overheid")
Bedrijfstak.create("letter"=>"P", "naam"=>"Onderwijs")
Bedrijfstak.create("letter"=>"Q", "naam"=>"Gezondheidszorg")
Bedrijfstak.create("letter"=>"R", "naam"=>"Recreatie")
Bedrijfstak.create("letter"=>"T", "naam"=>"Huishoudens")
Bedrijfstak.create("letter"=>"U", "naam"=>"Extraterritoriale organisaties")






Boekproces.create("naam"=>"Inkomsten 13", "icoon"=>nil, "kostenspecificatie"=>nil)


Boekproces.create("naam"=>"Betalingen", "icoon"=>nil, "kostenspecificatie"=>nil)
Boekproces.create("naam"=>"Toename recht (waardestijging)", "icoon"=>nil, "kostenspecificatie"=>nil)
Boekproces.create("naam"=>"Afname recht (waardedaling)", "icoon"=>nil, "kostenspecificatie"=>nil)
Boekproces.create("naam"=>"Toename plicht (waardedaling", "icoon"=>nil, "kostenspecificatie"=>nil)
Boekproces.create("naam"=>"Afname plicht (waardestijging", "icoon"=>nil, "kostenspecificatie"=>nil)
Boekproces.create("naam"=>"--, Vennootschapsbelasting", "icoon"=>nil, "kostenspecificatie"=>nil)
Boekproces.create("naam"=>"+, Vernnootschapsbelasting", "icoon"=>nil, "kostenspecificatie"=>nil)
Boekproces.create("naam"=>"- , Nog te betalen btw", "icoon"=>nil, "kostenspecificatie"=>nil)
Boekproces.create("naam"=>"+ , Nog te betalen btw", "icoon"=>nil, "kostenspecificatie"=>nil)
Boekproces.create("naam"=>"Rentelasten", "icoon"=>nil, "kostenspecificatie"=>nil)
Boekproces.create("naam"=>"Rentebaten", "icoon"=>nil, "kostenspecificatie"=>nil)
Boekproces.create("naam"=>"Opbrengst effecten", "icoon"=>nil, "kostenspecificatie"=>nil)
Boekproces.create("naam"=>"Waardeverandering effecten", "icoon"=>nil, "kostenspecificatie"=>nil)
Boekproces.create("naam"=>"Levering in (inkopen)", "icoon"=>nil, "kostenspecificatie"=>nil)
Boekproces.create("naam"=>"Afschrijving vaste activa", "icoon"=>nil, "kostenspecificatie"=>"kostensoorten")
Boekproces.create("naam"=>"Waardeverandering anders", "icoon"=>nil, "kostenspecificatie"=>"kostensoorten")
Boekproces.create("naam"=>"Lonen en salarissen", "icoon"=>nil, "kostenspecificatie"=>"kostensoorten")
Boekproces.create("naam"=>"Sociale lasten", "icoon"=>nil, "kostenspecificatie"=>"kostensoorten")
Boekproces.create("naam"=>"Afschrijvingen vaste activa", "icoon"=>nil, "kostenspecificatie"=>"kostensoorten")
Boekproces.create("naam"=>"Overige waardeveranderingen vaste activa", "icoon"=>nil, "kostenspecificatie"=>"kostensoorten")
Boekproces.create("naam"=>"Bijzondere waardevermindering vlottende activa", "icoon"=>nil, "kostenspecificatie"=>"kostensoorten")
Boekproces.create("naam"=>"Overige bedrijfskosten", "icoon"=>nil, "kostenspecificatie"=>"kostensoorten")
Boekproces.create("naam"=>"Inkoopwaarde van de omzet", "icoon"=>nil, "kostenspecificatie"=>"functionele kosten")
Boekproces.create("naam"=>"Inkoopkosten", "icoon"=>nil, "kostenspecificatie"=>"functionele kosten")
Boekproces.create("naam"=>"Verkoopkosten", "icoon"=>nil, "kostenspecificatie"=>"functionele kosten")
Boekproces.create("naam"=>"Algemene kosten", "icoon"=>nil, "kostenspecificatie"=>"functionele kosten")
Boekproces.create("naam"=>"Bedrijfskosten", "icoon"=>nil, "kostenspecificatie"=>"functionele kosten")
Boekproces.create("naam"=>"Levering uit (verkopen, omzet)", "icoon"=>nil, "kostenspecificatie"=>nil)
Boekproces.create("naam"=>"Basis winst", "icoon"=>nil, "kostenspecificatie"=>nil)
Boekproces.create("naam"=>"Dividend", "icoon"=>nil, "kostenspecificatie"=>nil)
Grootboekrekening.create("naam"=>"zelf gemaakt", "grootboektype_id"=>14, "organisatie_id"=>"1", "icoon"=>nil)
Grootboekrekening.create("naam"=>"boodschappen houdbaar", "grootboektype_id"=>12, "organisatie_id"=>"1", "icoon"=>nil)
Grootboekrekening.create("naam"=>"vervoersspullen", "grootboektype_id"=>13, "organisatie_id"=>"1", "icoon"=>nil)
Grootboekrekening.create("naam"=>"interieurspullen", "grootboektype_id"=>13, "organisatie_id"=>"1", "icoon"=>nil)
Grootboekrekening.create("naam"=>"kosten voor huis", "grootboektype_id"=>3, "organisatie_id"=>"1", "icoon"=>nil)
Grootboekrekening.create("naam"=>"energiekosten", "grootboektype_id"=>3, "organisatie_id"=>"1", "icoon"=>nil)
Grootboekrekening.create("naam"=>"schoonmakers", "grootboektype_id"=>4, "organisatie_id"=>"1", "icoon"=>nil)
Grootboekrekening.create("naam"=>"mijn huis", "grootboektype_id"=>14, "organisatie_id"=>"1", "icoon"=>nil)
Grootboekrekening.create("naam"=>"mijn werk", "grootboektype_id"=>16, "organisatie_id"=>"1", "icoon"=>nil)
Grootboekrekening.create("naam"=>"inkoop brood", "grootboektype_id"=>1, "organisatie_id"=>"2", "icoon"=>nil)
Grootboekrekening.create("naam"=>"Bank", "grootboektype_id"=>9, "organisatie_id"=>"2", "icoon"=>nil)
Grootboekrekening.create("naam"=>"BTW Inkopen", "grootboektype_id"=>10, "organisatie_id"=>"2", "icoon"=>nil)
Grootboekrekening.create("naam"=>"telefoonkosten", "grootboektype_id"=>3, "organisatie_id"=>"2", "icoon"=>nil)
Grootboekrekening.create("naam"=>"verkoop brood", "grootboektype_id"=>5, "organisatie_id"=>"2", "icoon"=>nil)
Grootboekrekening.create("naam"=>"lening 5%", "grootboektype_id"=>11, "organisatie_id"=>"2", "icoon"=>nil)
Grootboekrekening.create("naam"=>"BTW Verkopen", "grootboektype_id"=>10, "organisatie_id"=>"2", "icoon"=>nil)
Grootboekrekening.create("naam"=>"machines", "grootboektype_id"=>2, "organisatie_id"=>"2", "icoon"=>nil)
Grootboekrekening.create("naam"=>"leveringskosten", "grootboektype_id"=>3, "organisatie_id"=>"2", "icoon"=>nil)
Grootboekrekening.create("naam"=>"advertentie", "grootboektype_id"=>7, "organisatie_id"=>"2", "icoon"=>nil)
Grootboekrekening.create("naam"=>"administratie", "grootboektype_id"=>17, "organisatie_id"=>"2", "icoon"=>nil)
Grootboekrekening.create("naam"=>"boodschappen", "grootboektype_id"=>12, "organisatie_id"=>"1", "icoon"=>nil)
Grootboekrekening.create("naam"=>"Maxima", "grootboektype_id"=>4, "organisatie_id"=>"2", "icoon"=>nil)
Grootboekrekening.create("naam"=>"debiteuren", "grootboektype_id"=>8, "organisatie_id"=>"2", "icoon"=>nil)
Grootboekrekening.create("naam"=>"crediteuren", "grootboektype_id"=>8, "organisatie_id"=>"2", "icoon"=>nil)
Grootboekrekening.create("naam"=>"rente te betalen lening 5%", "grootboektype_id"=>11, "organisatie_id"=>"2", "icoon"=>nil)
Grootboekrekening.create("naam"=>"dividend", "grootboektype_id"=>18, "organisatie_id"=>"1", "icoon"=>nil)
Grootboektype.create("naam"=>"Vlottende activa", "icoon"=>nil, "categorie"=>"I")
Grootboektype.create("naam"=>"Vaste activa", "icoon"=>nil, "categorie"=>"I")
Grootboektype.create("naam"=>"Kosten", "icoon"=>nil, "categorie"=>"I")
Grootboektype.create("naam"=>"Personeel", "icoon"=>nil, "categorie"=>"I")
Grootboektype.create("naam"=>"Verkopen", "icoon"=>nil, "categorie"=>"O")
Grootboektype.create("naam"=>"Know-how", "icoon"=>nil, "categorie"=>"O")
Grootboektype.create("naam"=>"Reclame", "icoon"=>nil, "categorie"=>"O")
Grootboektype.create("naam"=>"Debiteuren en Crediteuren", "icoon"=>nil, "categorie"=>"D")
Grootboektype.create("naam"=>"Geld", "icoon"=>nil, "categorie"=>"D")
Grootboektype.create("naam"=>"Belastingen", "icoon"=>nil, "categorie"=>"D")
Grootboektype.create("naam"=>"Financiele producten", "icoon"=>nil, "categorie"=>"D")
Grootboektype.create("naam"=>"Niet-duurzame consumptiegoederen", "icoon"=>nil, "categorie"=>"N")
Grootboektype.create("naam"=>"Duurzame consumptiegoederen", "icoon"=>nil, "categorie"=>"N")
Grootboektype.create("naam"=>"Voor gezinsleden", "icoon"=>nil, "categorie"=>"N")
Grootboektype.create("naam"=>"Kennis (over huishouden, koken, sociale vaardigheden, etc.)", "icoon"=>nil, "categorie"=>"N")
Grootboektype.create("naam"=>"Arbeid bij bakker", "icoon"=>nil, "categorie"=>"N")
Grootboektype.create("naam"=>"Administratie", "icoon"=>nil, "categorie"=>"O")
Grootboektype.create("naam"=>"Dividend", "icoon"=>nil, "categorie"=>"D")
Journaal.create("journaaltype_id"=>1, "boeknummer"=>"ink-001", "datum"=>nil, "leverancier"=>"Leverancier A", "klant"=>nil, "hoeveelheid"=>300, "eenheid"=>"stuk", "productnaam"=>"Brood", "stukprijs"=>1, "betalingswijze"=>"Contant", "valuta"=>"euro", "btw_percentage"=>6, "bedrag_ex_btw"=>300, "bedrag_inc_btw"=>318, "organisatie_id"=>2, "voorwaarden"=>"inknr-0027\nVoorwaarde 1\nVoorwaarde 2\nVoorwaarde 3")
Journaal.create("journaaltype_id"=>1, "boeknummer"=>"ink-002", "datum"=>nil, "leverancier"=>"Leverancier B", "klant"=>nil, "hoeveelheid"=>1, "eenheid"=>"kilo", "productnaam"=>"Zout", "stukprijs"=>2, "betalingswijze"=>"Bank", "valuta"=>"euro", "btw_percentage"=>6, "bedrag_ex_btw"=>2, "bedrag_inc_btw"=>2, "organisatie_id"=>2, "voorwaarden"=>"inknr-0028\nVoorwaarde 1\nVoorwaarde 2\nVoorwaarde 3")
Journaal.create("journaaltype_id"=>2, "boeknummer"=>"Verk-001", "datum"=>nil, "leverancier"=>nil, "klant"=>"Diverse kopers", "hoeveelheid"=>300, "eenheid"=>"stuk", "productnaam"=>"Brood", "stukprijs"=>2, "betalingswijze"=>"Contant", "valuta"=>"euro", "btw_percentage"=>6, "bedrag_ex_btw"=>300, "bedrag_inc_btw"=>318, "organisatie_id"=>2, "voorwaarden"=>"Vernr-0001\nVoorwaarde 1\nVoorwaarde 2\nVoorwaarde 3")
Journaal.create("journaaltype_id"=>2, "boeknummer"=>"Verk-002", "datum"=>nil, "leverancier"=>nil, "klant"=>"Klant B", "hoeveelheid"=>10, "eenheid"=>"pot", "productnaam"=>"Jam", "stukprijs"=>5, "betalingswijze"=>"Bank", "valuta"=>"euro", "btw_percentage"=>6, "bedrag_ex_btw"=>50, "bedrag_inc_btw"=>53, "organisatie_id"=>2, "voorwaarden"=>"Vernr-0002\nVoorwaarde 1\nVoorwaarde 2\nVoorwaarde 3")
Journaal.create("journaaltype_id"=>3, "boeknummer"=>"Afschrift-001", "datum"=>nil, "leverancier"=>nil, "klant"=>"Koper A", "hoeveelheid"=>nil, "eenheid"=>nil, "productnaam"=>nil, "stukprijs"=>nil, "betalingswijze"=>nil, "valuta"=>"euro", "btw_percentage"=>nil, "bedrag_ex_btw"=>nil, "bedrag_inc_btw"=>318, "organisatie_id"=>2, "voorwaarden"=>"Afschrift-0001\nBehorende bij Vernr-0001")
Journaal.create("journaaltype_id"=>3, "boeknummer"=>"Afschrift-002", "datum"=>nil, "leverancier"=>"Leverancier A", "klant"=>nil, "hoeveelheid"=>nil, "eenheid"=>nil, "productnaam"=>nil, "stukprijs"=>nil, "betalingswijze"=>nil, "valuta"=>"euro", "btw_percentage"=>nil, "bedrag_ex_btw"=>nil, "bedrag_inc_btw"=>-318, "organisatie_id"=>2, "voorwaarden"=>"Afschrift-0001\nBehorende bij inknr-0001")
Journaal.create("journaaltype_id"=>4, "boeknummer"=>"Levering-001", "datum"=>nil, "leverancier"=>nil, "klant"=>"Koper A", "hoeveelheid"=>300, "eenheid"=>"stuk", "productnaam"=>"Brood", "stukprijs"=>nil, "betalingswijze"=>nil, "valuta"=>"euro", "btw_percentage"=>nil, "bedrag_ex_btw"=>2, "bedrag_inc_btw"=>nil, "organisatie_id"=>2, "voorwaarden"=>"Levering-0001\nBehorende bij Vernr-0001")
Journaal.create("journaaltype_id"=>4, "boeknummer"=>"Levering-002", "datum"=>nil, "leverancier"=>"Leverancier A", "klant"=>nil, "hoeveelheid"=>10, "eenheid"=>"kilo", "productnaam"=>"Meel", "stukprijs"=>nil, "betalingswijze"=>nil, "valuta"=>"euro", "btw_percentage"=>nil, "bedrag_ex_btw"=>2, "bedrag_inc_btw"=>nil, "organisatie_id"=>2, "voorwaarden"=>"levering-0002\nBehorende bij inknr-0001")
Journaal.create("journaaltype_id"=>5, "boeknummer"=>"Feit-001", "datum"=>nil, "leverancier"=>nil, "klant"=>nil, "hoeveelheid"=>nil, "eenheid"=>nil, "productnaam"=>nil, "stukprijs"=>nil, "betalingswijze"=>nil, "valuta"=>nil, "btw_percentage"=>nil, "bedrag_ex_btw"=>nil, "bedrag_inc_btw"=>nil, "organisatie_id"=>2, "voorwaarden"=>"We schrijven de oven in 5 jaar af")
Journaal.create("journaaltype_id"=>5, "boeknummer"=>"Feit-002", "datum"=>nil, "leverancier"=>nil, "klant"=>nil, "hoeveelheid"=>nil, "eenheid"=>nil, "productnaam"=>nil, "stukprijs"=>nil, "betalingswijze"=>nil, "valuta"=>nil, "btw_percentage"=>nil, "bedrag_ex_btw"=>nil, "bedrag_inc_btw"=>nil, "organisatie_id"=>2, "voorwaarden"=>"De rente op onze lening van 20000 euro is 5 procent per jaar")
Journaal.create("journaaltype_id"=>1, "boeknummer"=>"rente 1", "datum"=>nil, "leverancier"=>"Bank ", "klant"=>"", "hoeveelheid"=>1, "eenheid"=>"1", "productnaam"=>"Rente 5%", "stukprijs"=>1000, "betalingswijze"=>"bank", "valuta"=>"euro", "btw_percentage"=>nil, "bedrag_ex_btw"=>nil, "bedrag_inc_btw"=>nil, "organisatie_id"=>1, "voorwaarden"=>"")
Journaaltype.create("naam"=>" Inkoopboek", "icoon"=>nil)
Journaaltype.create("naam"=>"Verkoopboek", "icoon"=>nil)
Journaaltype.create("naam"=>"Bankboek", "icoon"=>nil)
Journaaltype.create("naam"=>"Leveringen", "icoon"=>nil)
Journaaltype.create("naam"=>"Intern", "icoon"=>nil)
Mens.create("naam"=>"Thijs", "leeftijd"=>49, "geslacht"=>"man", "kennisniveau"=>"4", "gezondheidsniveau"=>"4", "geluksniveau"=>"4")
Mens.create("naam"=>"Maxima", "leeftijd"=>24, "geslacht"=>"vrouw", "kennisniveau"=>"3", "gezondheidsniveau"=>"5", "geluksniveau"=>"4")
Mens.create("naam"=>"Bert de Bakker", "leeftijd"=>34, "geslacht"=>"man", "kennisniveau"=>"4", "gezondheidsniveau"=>"4", "geluksniveau"=>"4")
Organisatie.create("naam"=>"Maxima", "bedrijfstak_id"=>19, "rechtsvorm_id"=>1, "voorkant_image"=>nil)
Organisatie.create("naam"=>"Bakker Bart", "bedrijfstak_id"=>7, "rechtsvorm_id"=>2, "voorkant_image"=>nil)
Organisatie.create("naam"=>"MediaMarkt", "bedrijfstak_id"=>7, "rechtsvorm_id"=>10, "voorkant_image"=>nil)
Organisatie.create("naam"=>"Shell", "bedrijfstak_id"=>3, "rechtsvorm_id"=>10, "voorkant_image"=>nil)
Organisatie.create("naam"=>"Bank ING", "bedrijfstak_id"=>11, "rechtsvorm_id"=>11, "voorkant_image"=>nil)
Organisatie.create("naam"=>"Parlement", "bedrijfstak_id"=>15, "rechtsvorm_id"=>12, "voorkant_image"=>nil)
Product.create("naam"=>"Brood", "icoon"=>nil)
Product.create("naam"=>"Oven", "icoon"=>nil)
Rechtsvorm.create("naam"=>"Gezin", "afkorting"=>"gzn", "sector"=>"Huishoudens")
Rechtsvorm.create("naam"=>"Eenmanszaak", "afkorting"=>"zzp", "sector"=>"Huishoudens")
Rechtsvorm.create("naam"=>"Maatschap", "afkorting"=>"MS", "sector"=>"Huishoudens")
Rechtsvorm.create("naam"=>"Vennootschap Onder Firma", "afkorting"=>"V.O.F.", "sector"=>"Huishoudens")
Rechtsvorm.create("naam"=>"Commanditaire Vennootschap", "afkorting"=>"C.V.", "sector"=>"Huishoudens")
Rechtsvorm.create("naam"=>"Vereniging", "afkorting"=>"ver", "sector"=>"Huishoudens")
Rechtsvorm.create("naam"=>"Co\xC3\xB6peratie/Onderlinge waarborgmaatschappij", "afkorting"=>"COWM", "sector"=>"Huishoudens")
Rechtsvorm.create("naam"=>"Stichting", "afkorting"=>"ST", "sector"=>"Huishoudens")
Rechtsvorm.create("naam"=>"B.V.", "afkorting"=>"B.V.", "sector"=>"Vennootschappen")
Rechtsvorm.create("naam"=>"N.V.", "afkorting"=>"N.V.", "sector"=>"Vennootschappen")
Rechtsvorm.create("naam"=>"Vennootschap met bankvergunning", "afkorting"=>"FI", "sector"=>"Financi\xC3\xABle_instelling")
Rechtsvorm.create("naam"=>"Overheid", "afkorting"=>"Ov", "sector"=>"Overheid")

Boeking.create("grootboekrekening_id"=>11, "journaal_id"=>1, "product_id"=>1, "datum"=>nil, "icoon"=>nil, "bij_af"=>"-", "waarde"=>106000, "p_inkoop"=>0, "hoeveelheid"=>0, "organisatie_id"=>2, "boekingtype"=>"J", "boekproces_id"=>2)
Boeking.create("grootboekrekening_id"=>12, "journaal_id"=>1, "product_id"=>1, "datum"=>nil, "icoon"=>nil, "bij_af"=>"+", "waarde"=>6000, "p_inkoop"=>0, "hoeveelheid"=>0, "organisatie_id"=>2, "boekingtype"=>"J", "boekproces_id"=>10)
Boeking.create("grootboekrekening_id"=>10, "journaal_id"=>9, "product_id"=>1, "datum"=>nil, "icoon"=>nil, "bij_af"=>"-", "waarde"=>100000, "p_inkoop"=>1, "hoeveelheid"=>100000, "organisatie_id"=>2, "boekingtype"=>"I", "boekproces_id"=>24)
Boeking.create("grootboekrekening_id"=>13, "journaal_id"=>9, "product_id"=>1, "datum"=>nil, "icoon"=>nil, "bij_af"=>"-", "waarde"=>8000, "p_inkoop"=>1, "hoeveelheid"=>1, "organisatie_id"=>2, "boekingtype"=>"I", "boekproces_id"=>25)
Boeking.create("grootboekrekening_id"=>13, "journaal_id"=>9, "product_id"=>1, "datum"=>nil, "icoon"=>nil, "bij_af"=>"-", "waarde"=>12000, "p_inkoop"=>1, "hoeveelheid"=>1, "organisatie_id"=>2, "boekingtype"=>"I", "boekproces_id"=>26)
Boeking.create("grootboekrekening_id"=>13, "journaal_id"=>9, "product_id"=>1, "datum"=>nil, "icoon"=>nil, "bij_af"=>"-", "waarde"=>20000, "p_inkoop"=>1, "hoeveelheid"=>1, "organisatie_id"=>2, "boekingtype"=>"I", "boekproces_id"=>27)
Boeking.create("grootboekrekening_id"=>14, "journaal_id"=>4, "product_id"=>1, "datum"=>nil, "icoon"=>nil, "bij_af"=>"-", "waarde"=>100000, "p_inkoop"=>1, "hoeveelheid"=>1, "organisatie_id"=>2, "boekingtype"=>"I", "boekproces_id"=>29)
Boeking.create("grootboekrekening_id"=>16, "journaal_id"=>9, "product_id"=>1, "datum"=>nil, "icoon"=>nil, "bij_af"=>"-", "waarde"=>12000, "p_inkoop"=>1, "hoeveelheid"=>1, "organisatie_id"=>2, "boekingtype"=>"I", "boekproces_id"=>9)
Boeking.create("grootboekrekening_id"=>11, "journaal_id"=>3, "product_id"=>1, "datum"=>nil, "icoon"=>nil, "bij_af"=>"+", "waarde"=>212000, "p_inkoop"=>nil, "hoeveelheid"=>nil, "organisatie_id"=>2, "boekingtype"=>"", "boekproces_id"=>1)
Boeking.create("grootboekrekening_id"=>11, "journaal_id"=>2, "product_id"=>1, "datum"=>nil, "icoon"=>nil, "bij_af"=>"-", "waarde"=>56870, "p_inkoop"=>nil, "hoeveelheid"=>nil, "organisatie_id"=>2, "boekingtype"=>"", "boekproces_id"=>2)
Boeking.create("grootboekrekening_id"=>12, "journaal_id"=>1, "product_id"=>1, "datum"=>nil, "icoon"=>nil, "bij_af"=>"+", "waarde"=>9870, "p_inkoop"=>nil, "hoeveelheid"=>nil, "organisatie_id"=>2, "boekingtype"=>"", "boekproces_id"=>10)
Boeking.create("grootboekrekening_id"=>15, "journaal_id"=>1, "product_id"=>1, "datum"=>nil, "icoon"=>nil, "bij_af"=>"-", "waarde"=>20000, "p_inkoop"=>nil, "hoeveelheid"=>nil, "organisatie_id"=>2, "boekingtype"=>"", "boekproces_id"=>15)
Boeking.create("grootboekrekening_id"=>14, "journaal_id"=>3, "product_id"=>1, "datum"=>nil, "icoon"=>nil, "bij_af"=>"-", "waarde"=>100000, "p_inkoop"=>nil, "hoeveelheid"=>nil, "organisatie_id"=>2, "boekingtype"=>"J", "boekproces_id"=>29)
Boeking.create("grootboekrekening_id"=>1, "journaal_id"=>11, "product_id"=>1, "datum"=>nil, "icoon"=>nil, "bij_af"=>"+", "waarde"=>900, "p_inkoop"=>nil, "hoeveelheid"=>nil, "organisatie_id"=>1, "boekingtype"=>"J", "boekproces_id"=>1)
Boeking.create("grootboekrekening_id"=>17, "journaal_id"=>1, "product_id"=>1, "datum"=>nil, "icoon"=>nil, "bij_af"=>"-", "waarde"=>3000, "p_inkoop"=>nil, "hoeveelheid"=>nil, "organisatie_id"=>2, "boekingtype"=>"", "boekproces_id"=>20)
Boeking.create("grootboekrekening_id"=>17, "journaal_id"=>1, "product_id"=>2, "datum"=>nil, "icoon"=>nil, "bij_af"=>"+", "waarde"=>10000, "p_inkoop"=>10000, "hoeveelheid"=>1, "organisatie_id"=>2, "boekingtype"=>"", "boekproces_id"=>15)
Boeking.create("grootboekrekening_id"=>13, "journaal_id"=>1, "product_id"=>1, "datum"=>nil, "icoon"=>nil, "bij_af"=>"+", "waarde"=>37000, "p_inkoop"=>nil, "hoeveelheid"=>nil, "organisatie_id"=>2, "boekingtype"=>"", "boekproces_id"=>15)
Boeking.create("grootboekrekening_id"=>13, "journaal_id"=>1, "product_id"=>1, "datum"=>nil, "icoon"=>nil, "bij_af"=>"-", "waarde"=>37000, "p_inkoop"=>nil, "hoeveelheid"=>nil, "organisatie_id"=>2, "boekingtype"=>"", "boekproces_id"=>23)
Boeking.create("grootboekrekening_id"=>10, "journaal_id"=>1, "product_id"=>1, "datum"=>nil, "icoon"=>nil, "bij_af"=>"+", "waarde"=>100000, "p_inkoop"=>1, "hoeveelheid"=>100000, "organisatie_id"=>2, "boekingtype"=>"", "boekproces_id"=>15)
Boeking.create("grootboekrekening_id"=>15, "journaal_id"=>1, "product_id"=>1, "datum"=>nil, "icoon"=>nil, "bij_af"=>"-", "waarde"=>1000, "p_inkoop"=>nil, "hoeveelheid"=>nil, "organisatie_id"=>2, "boekingtype"=>"", "boekproces_id"=>11)
Boeking.create("grootboekrekening_id"=>26, "journaal_id"=>1, "product_id"=>1, "datum"=>nil, "icoon"=>nil, "bij_af"=>"-", "waarde"=>40000, "p_inkoop"=>nil, "hoeveelheid"=>nil, "organisatie_id"=>2, "boekingtype"=>"Dividend", "boekproces_id"=>31)
